CREATE TABLE coalitionmpi.sftp_file_transfer
(
    sftp_file_transfer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    path text NOT NULL,
	file_name text NOT NULL,
	last_modified timestamp without time zone NOT NULL,
	transfer_date_time timestamp without time zone NOT NULL,
	status character varying(100) NOT NULL,
    CONSTRAINT "PK_sftp_file_transfer" PRIMARY KEY (sftp_file_transfer_id)
)