<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Extensions\" />
    <None Remove="Extensions\ModelExtensions\" />
    <None Remove="Comparer\" />
    <None Remove="Logger\" />
    <None Remove="Amazon.Lambda.Core" />
    <None Remove="Microsoft.Extensions.DependencyInjection" />
    <None Remove="Http\" />
    <None Remove="Exceptions\" />
    <None Remove="Security\" />
    <None Remove="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <None Remove="Converters\" />
    <None Remove="FileReadWriter\" />
    <None Remove="AWSSDK.S3" />
    <None Remove="Attributes\" />
    <None Remove="Sqs\" />
    <None Remove="AWSSDK.SQS" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Extensions\ModelExtensions\" />
    <Folder Include="Comparer\" />
    <Folder Include="Logger\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Security\" />
    <Folder Include="Converters\" />
    <Folder Include="FileReadWriter\" />
    <Folder Include="Attributes\" />
    <Folder Include="Sqs\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HCA.Models\HCA.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.2.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.103.13" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.7.304.4" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.2.97" />
    <PackageReference Include="SSH.NET" Version="2020.0.2" />
    <PackageReference Include="Amazon.S3" Version="0.24.0" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.9.23" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>