<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Microsoft.Extensions.DependencyInjection" />
    <None Remove="MuleSoft\" />
    <None Remove="Requests\" />
    <None Remove="Enums\" />
    <None Remove="MuleSoft\Request\" />
    <None Remove="MuleSoft\Response\" />
    <None Remove="Request\" />
    <None Remove="Response\" />
    <None Remove="SQS\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.100.16" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="MuleSoft\" />
    <Folder Include="Enums\" />
    <Folder Include="MuleSoft\Request\" />
    <Folder Include="MuleSoft\Response\" />
    <Folder Include="Request\" />
    <Folder Include="Response\" />
    <Folder Include="SQS\" />
  </ItemGroup>
</Project>
