using HCA.Core.Mapper;
using HCA.Core.Services;
using HCA.Data.Repository;
using HCA.Infrastructure.Logger;
using HCA.Models.Enums;
using HCA.Models.MuleSoft;
using HCA.Models.Request;
using HCA.Models.Response;
using Newtonsoft.Json.Linq;
using System.Text.Json;

namespace HCA.Core.Processors.MPIDBSync
{
    public class MPIDBSynchronizer(
        IAppLogger logger,
        IClientIdentityRequestRepository clientIdentityRequestRepository,
        IClientIdentityRequestExecutor clientIdentityRequestExecutor,
        IClientIdentityRepository clientIdentityRepository,
        IRequestProcessLogRepository requestProcessLogRepository ) : IMPIDBSynchronizer
    {
        private readonly IAppLogger _logger = logger;
        private readonly IClientIdentityRequestRepository _clientIdentityRequestRepository = clientIdentityRequestRepository;
        private readonly IClientIdentityRequestExecutor _clientIdentityRequestExecutor = clientIdentityRequestExecutor;
        private readonly IRequestProcessLogRepository _requestProcessLogRepository = requestProcessLogRepository;
        private readonly IClientIdentityRepository _clientIdentityRepository = clientIdentityRepository;
        private static readonly JsonSerializerOptions CachedJsonSerializerOptions = new()
        {
            PropertyNameCaseInsensitive = true
        };


        public async Task SyncMPIDB()
        {
            _logger.LogInformation( "Starting MPIDB synchronization..." );

            try
            {
                DateTime startTime = DateTime.UtcNow.AddMinutes(-30);
                DateTime endTime = DateTime.UtcNow;

                _logger.LogInformation( $"Querying Verato Notifications from {startTime} to {endTime}" );

                ClientIdentityRequestStatusUpdater requestStatusUpdater = new ClientIdentityRequestStatusUpdater(_clientIdentityRequestRepository, _requestProcessLogRepository);

                await ProcessVeratoNotificationsAsync(startTime, endTime, requestStatusUpdater);

                _logger.LogInformation( "MPIDB synchronization completed successfully." );
            }
            catch( Exception ex )
            {
                _logger.LogError( ex, "An error occurred during MPIDB synchronization." );
                throw;
            }
        }

        private async Task ProcessVeratoNotificationsAsync( DateTime startTime, DateTime endTime, ClientIdentityRequestStatusUpdater requestStatusUpdater)
        {
            int pageNumber = 0;
            const int pageSize = 100;
            bool hasNext = true;
            int notificationsProcessed = 0;

            List<ClientIdentityNotification> allNotifications = new List<ClientIdentityNotification>();

            while (hasNext)
            {
                SearchClientIdentityNotificationsRequest veratoSearchNotificationRequest = new SearchClientIdentityNotificationsRequest("")
                {
                    Content = new SearchClientIdentityNotificationsRequestContent
                    {
                        PageNumber = pageNumber,
                        PageSize = pageSize,
                        StartDate = startTime,
                        EndDate = endTime
                    }
                };

                SearchClientIdentityNotificationResponse? response = await _clientIdentityRequestExecutor.Execute<SearchClientIdentityNotificationResponse>(veratoSearchNotificationRequest, requestStatusUpdater);

                if (response?.Content?.Notifications != null)
                {
                    //filter the notifications excluding the ones generated by MPI
                    var eligibleNotifications = response.Content.Notifications.Where(n => n.Username != "wadoh.umpi.cust0131-dev.2022.04");

                    notificationsProcessed += eligibleNotifications.Count();

                    await ProcessVeratoNotificationsBatchAsync(eligibleNotifications.ToList(), requestStatusUpdater);

                    hasNext = response.Content.HasNext;
                    pageNumber++;
                }
                else
                {
                    _logger.LogInformation("Received null or empty response from Verato.");
                    break;
                }
            }

            _logger.LogInformation($"Total eligible notifications processed: {notificationsProcessed}");

        }

        private async Task ProcessVeratoNotificationsBatchAsync(List<ClientIdentityNotification> veratoNotifications, ClientIdentityRequestStatusUpdater requestStatusUpdater)
        {
            foreach (ClientIdentityNotification notification in veratoNotifications)
            {
                bool isDelete = false;
                bool isHardDelete = false;
                using JsonDocument doc = JsonDocument.Parse(notification.Body);
                JsonElement root = doc.RootElement;

                string? source = root.GetProperty("source").GetString();
                string? nativeId = root.GetProperty("nativeId").GetString();

                if (source == null || nativeId == null)
                {
                    continue;
                }

                _logger.LogInformation($"Processing notification for source:{source} and nativeId:{nativeId}");

                //TODO: Map the notification types and take appropriate actions
                //VeratoNotificationTypes
                if (Enum.TryParse<VeratoNotificationTypes>(notification.NotificationType, ignoreCase: true, out var notificationType))
                {
                    _logger.LogInformation($"Verato NotificationType:{notificationType}");

                    switch (notificationType)
                    {
                        case VeratoNotificationTypes.SourceDeleted:
                        case VeratoNotificationTypes.SourceDeactivated:
                            isDelete = true;
                            break;

                        case VeratoNotificationTypes.HardDeleted:
                            isDelete = true;
                            isHardDelete = true;
                            break;

                        case VeratoNotificationTypes.IdentityEnriched:
                            _logger.LogInformation($"Skip processing notification for {notificationType}");
                            continue;

                        default:
                            break;

                    }
                }

                if(isHardDelete)
                {
                    var existingIdentity = await _clientIdentityRepository.GetBySource(source, nativeId);
                    if (existingIdentity != null)
                    {
                        existingIdentity.IsActive = !isHardDelete;
                        existingIdentity.IsDelete = isHardDelete;

                        await _clientIdentityRepository.Upsert(existingIdentity, isHardDelete);
                    }
                    else
                    {
                        _logger.LogWarning($"Verato deleted identity with Source: {source} and NativeId: {nativeId} is not found in MPI");
                    }

                    continue;

                }

                NativeIdQueryClientIdentityRequest nativeIdQueryRequest = new NativeIdQueryClientIdentityRequest("")
                {
                    Content = new NativeIdQueryContent()
                    {
                        Source = new HCA.Models.Request.NativeIdRequestSource()
                        {
                            Name = source,
                            Id = nativeId
                        }
                    }
                };

                NativeIdQueryClientIdentityResponse? nativeIdResponse = await _clientIdentityRequestExecutor.Execute<NativeIdQueryClientIdentityResponse>(nativeIdQueryRequest, requestStatusUpdater);

                dynamic serializedContent = JsonSerializer.Serialize(nativeIdResponse?.Content);

                JObject obj = JObject.Parse(serializedContent);

                if (obj == null || !obj.ContainsKey("identity"))
                {
                    _logger.LogWarning($"No identity found for notification with nativeId: {nativeId}");
                    continue;
                }
                else
                {
                    JObject? identity = (JObject?)obj?["identity"];

                    if (identity != null)
                    {
                        JArray? sources = identity["sources"] as JArray;
                        if (sources != null)
                        {
                            // Keep only the source from notification
                            var filteredSources = new JArray(
                                sources.Where(source => (string?)source?["id"] == nativeId)
                            );

                            identity["sources"] = filteredSources;
                        }

                        Identity? content = JsonSerializer.Deserialize<Identity>(identity.ToString(), CachedJsonSerializerOptions);

                        string? linkId = obj?["linkId"]?.ToString();

                        if (!string.IsNullOrEmpty(linkId) && content != null)
                        {
                            Data.Entities.ClientIdentityEntity entity = NewClientIdentityMapper.MapIdentityToClientIdentityEntity(linkId, DateTime.Now, content, isDelete);

                            var existingIdentity = await _clientIdentityRepository.GetBySource(source, nativeId);

                            if(existingIdentity != null)
                            {
                                entity.ProtectedPopulationFlag = existingIdentity.ProtectedPopulationFlag;
                                entity.ProtectedPopulationType = !string.IsNullOrEmpty(existingIdentity.ProtectedPopulationType) ? existingIdentity.ProtectedPopulationType :"";
                            }

                            await _clientIdentityRepository.Upsert(entity, isDelete);
                        }
                    }
                }
            }
        }
    }
}
