<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entities\" />
    <None Remove="Microsoft.EntityFrameworkCore" />
    <None Remove="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <None Remove="Microsoft.EntityFrameworkCore.Design" />
    <None Remove="Repository\" />
    <None Remove="Microsoft.Extensions.DependencyInjection" />
    <None Remove="AutoFilterer" />
    <None Remove="Repository\Core\" />
    <None Remove="Repository\Impl\" />
    <None Remove="Options\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repository\Core\" />
    <Folder Include="Options\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.6" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="AutoFilterer" Version="2.12.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HCA.Models\HCA.Models.csproj" />
    <ProjectReference Include="..\HCA.Infrastructure\HCA.Infrastructure.csproj" />
  </ItemGroup>
</Project>
