-- Table: custom_data_mapping

-- DROP TABLE IF EXISTS custom_data_mapping;

CREATE TABLE IF NOT EXISTS custom_data_mapping
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_system_name character varying(1000) NULL,
    input_index integer NULL,
    input_column_name character varying(3000) NULL,
    verato_request_path character varying(3000) NULL,
    verato_response_path character varying(3000) NULL,
    api_response_path character varying(3000) NULL,
    output_index integer NULL,
    output_column_name character varying(3000) NULL,
    CONSTRAINT custom_data_mapping_pkey PRIMARY KEY (id)
)
	 DO $$
  BEGIN
	  IF (select count(*) from custom_data_mapping) = 0
	  THEN	 
		INSERT INTO custom_data_mapping(
		source_system_name, input_index, input_column_name, verato_request_path, verato_response_path, api_response_path, output_index, output_column_name)
		VALUES (
			'wadoh.wdrs',
			0, 
			'createdDate',
			'custom.data$createdDate',
			'custom.data$createdDate', 
			'custom.data$createdDate', 
			0, 
			'createdDate'
				);
	  END IF;
  END $$;
  


-- Table: service_accounts

-- DROP TABLE IF EXISTS service_accounts;

CREATE TABLE IF NOT EXISTS service_accounts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_system_name character varying(1000) NULL,
    app_id character varying(1000) NULL,
    CONSTRAINT service_accounts_pkey PRIMARY KEY (id)
)


	 DO $$
  BEGIN
	  IF (select count(*) from service_accounts) = 0
	  THEN
		 INSERT INTO service_accounts(
 		source_system_name, app_id)
		VALUES (
			'WAHCA.Providerone', 
			'99be4864-532b-4432-9a6c-2f364a10532d'
	      	 	);
	  END IF;
  END $$;


  Alter Table client_identity_requests
  Add custom_json text NULL;
  
  Alter Table client_identity 
  Add custom_json text NULL;