CREATE TABLE client_identity (
    mpi_link_id character varying(1024) NOT NULL,
    source_system_name character varying(100) NOT NULL,
    source_system_id character varying(100) NOT NULL,
    source_system_agency character varying(100) NOT NULL,
    first_name character varying(40) NOT NULL,
    middle_name character varying(40) NULL,
    last_name character varying(40) NOT NULL,
    name_suffix character varying(40) NULL,
    ssn character varying(12) NOT NULL,
    dob date NULL,
    gender character varying(10) NOT NULL,
    protected_population_flag boolean NOT NULL,
    protected_population_type character varying(100) NOT NULL,
    mpi_updated timestamp without time zone NULL,
    source_system_updated timestamp without time zone NOT NULL,
    expiry_date timestamp without time zone NULL,
    is_active boolean NOT NULL,
    is_delete boolean NOT NULL,
    created_by character varying(255) NOT NULL,
    created_date timestamp without time zone NOT NULL,
    updated_by character varying(255) NULL,
    updated_date timestamp without time zone NULL,
    CONSTRAINT "PK_client_identity" PRIMARY KEY (mpi_link_id, source_system_name, source_system_id)
);


CREATE TABLE client_identity_requests (
    client_identity_request_id integer GENERATED BY DEFAULT AS IDENTITY,
    request_id integer NOT NULL,
    tracking_id character varying(1024) NOT NULL,
    mpi_link_id character varying(1024) NULL,
    source_system_updated timestamp without time zone NOT NULL,
    source_system_name character varying(100) NOT NULL,
    source_system_id character varying(100) NOT NULL,
    source_system_agency character varying(100) NOT NULL,
    first_name character varying(40) NOT NULL,
    middle_name character varying(40) NULL,
    last_name character varying(40) NOT NULL,
    name_suffix character varying(40) NULL,
    ssn character varying(12) NOT NULL,
    dob date NULL,
    gender character varying(10) NOT NULL,
    protected_population_flag boolean NOT NULL,
    protected_population_type character varying(100) NOT NULL,
    address_type character varying(40) NOT NULL,
    address_line_1 character varying(255) NOT NULL,
    address_line_2 character varying(255) NULL,
    address_line_3 character varying(255) NULL,
    city character varying(100) NOT NULL,
    state character varying(40) NOT NULL,
    zip_code character varying(5) NOT NULL,
    zip_four character varying(4) NOT NULL,
    phone_type character varying(40) NOT NULL,
    email_type character varying(40) NOT NULL,
    phone_number character varying(20) NOT NULL,
    email_address character varying(255) NOT NULL,
    status text NULL,
    message text NOT NULL,
    retry_count integer NOT NULL,
    CONSTRAINT "PK_client_identity_requests" PRIMARY KEY (client_identity_request_id)
);


CREATE TABLE file_requests (
    file_request_id integer GENERATED BY DEFAULT AS IDENTITY,
    tracking_id character varying(1024) NOT NULL,
    file_name character varying(1024) NOT NULL,
    output_file_name character varying(1024) NULL,
    source_system_agency character varying(100) NOT NULL,
    source_system_name character varying(100) NOT NULL,
    records_count integer NOT NULL,
    trailer character varying(100) NOT NULL,
    api_type character varying(40) NOT NULL,
    file_created_date_time timestamp without time zone NOT NULL,
    request_date_time timestamp without time zone NOT NULL,
    process_start_time timestamp without time zone NULL,
    process_end_time timestamp without time zone NULL,
    status character varying(40) NOT NULL,
    message text NOT NULL,
    CONSTRAINT "PK_file_requests" PRIMARY KEY (file_request_id)
);


CREATE TABLE mpi_link_id_history (
    mpi_link_history_id integer GENERATED BY DEFAULT AS IDENTITY,
    previous_mpi_link_id text NOT NULL,
    previous_source_system_name text NOT NULL,
    previous_source_system_id text NOT NULL,
    current_mpi_link_id text NOT NULL,
    current_source_system_name text NOT NULL,
    current_source_system_id text NOT NULL,
    created_by character varying(255) NOT NULL,
    created_date timestamp without time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    updated_date timestamp without time zone NOT NULL,
    CONSTRAINT "PK_mpi_link_id_history" PRIMARY KEY (mpi_link_history_id)
);


CREATE TABLE request_process_logs (
    request_process_log_id integer GENERATED BY DEFAULT AS IDENTITY,
    request_id uuid NOT NULL,
    date_time timestamp without time zone NOT NULL,
    message text NOT NULL,
    CONSTRAINT "PK_request_process_logs" PRIMARY KEY (request_process_log_id)
);


CREATE TABLE roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY (role_id)
);


CREATE TABLE user_requests (
    user_request_id integer GENERATED BY DEFAULT AS IDENTITY,
    tracking_id character varying(1024) NOT NULL,
    user_id integer NOT NULL,
    request_json text NOT NULL,
    request_date_time timestamp without time zone NOT NULL,
    process_start_time timestamp without time zone NOT NULL,
    process_end_time timestamp without time zone NULL,
    status character varying(40) NOT NULL,
    message text NOT NULL,
    retry_count integer NOT NULL,
    CONSTRAINT "PK_user_requests" PRIMARY KEY (user_request_id)
);


CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL,
    password character varying(1024) NOT NULL,
    first_name character varying(255) NOT NULL,
    middle_name character varying(255) NULL,
    last_name character varying(255) NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (user_id)
);


CREATE TABLE client_identity_address (
    client_identity_address_id integer GENERATED BY DEFAULT AS IDENTITY,
    mpi_link_id character varying(1024) NOT NULL,
    source_system_name character varying(100) NOT NULL,
    source_system_id character varying(100) NOT NULL,
    address_type character varying(40) NOT NULL,
    address_line_1 character varying(255) NOT NULL,
    address_line_2 character varying(255) NULL,
    address_line_3 character varying(255) NULL,
    city character varying(100) NOT NULL,
    state character varying(40) NOT NULL,
    zip_code character varying(5) NOT NULL,
    zip_four character varying(4) NOT NULL,
    source_system_updated timestamp without time zone NOT NULL,
    expiry_date timestamp without time zone NULL,
    is_active boolean NOT NULL,
    is_delete boolean NOT NULL,
    created_by character varying(255) NOT NULL,
    created_date timestamp without time zone NOT NULL,
    updated_by character varying(255) NULL,
    updated_date timestamp without time zone NULL,
    CONSTRAINT "PK_client_identity_address" PRIMARY KEY (client_identity_address_id),
    CONSTRAINT "FK_client_identity_address_client_identity_mpi_link_id_source_~" FOREIGN KEY (mpi_link_id, source_system_name, source_system_id) REFERENCES client_identity (mpi_link_id, source_system_name, source_system_id) ON DELETE CASCADE
);


CREATE TABLE client_identity_communication (
    client_identity_communication_id integer GENERATED BY DEFAULT AS IDENTITY,
    mpi_link_id character varying(1024) NOT NULL,
    source_system_name character varying(100) NOT NULL,
    source_system_id character varying(100) NOT NULL,
    phone_type character varying(40) NOT NULL,
    email_type character varying(40) NOT NULL,
    phone_number character varying(20) NOT NULL,
    email_address character varying(255) NOT NULL,
    source_system_updated timestamp without time zone NOT NULL,
    expiry_date timestamp without time zone NULL,
    is_active boolean NOT NULL,
    is_delete boolean NOT NULL,
    created_by character varying(255) NOT NULL,
    created_date timestamp without time zone NOT NULL,
    updated_by character varying(255) NULL,
    updated_date timestamp without time zone NULL,
    CONSTRAINT "PK_client_identity_communication" PRIMARY KEY (client_identity_communication_id),
    CONSTRAINT "FK_client_identity_communication_client_identity_mpi_link_id_s~" FOREIGN KEY (mpi_link_id, source_system_name, source_system_id) REFERENCES client_identity (mpi_link_id, source_system_name, source_system_id) ON DELETE CASCADE
);


CREATE TABLE user_roles (
    role_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT "PK_user_roles" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_user_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE CASCADE,
    CONSTRAINT "FK_user_roles_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);


CREATE TABLE client_identity_address_communication (
    client_identity_address_id integer NOT NULL,
    client_identity_communication_id integer NOT NULL,
    CONSTRAINT "PK_client_identity_address_communication" PRIMARY KEY (client_identity_address_id, client_identity_communication_id),
    CONSTRAINT "FK_client_identity_address_communication_client_identity_addre~" FOREIGN KEY (client_identity_address_id) REFERENCES client_identity_address (client_identity_address_id) ON DELETE CASCADE,
    CONSTRAINT "FK_client_identity_address_communication_client_identity_commu~" FOREIGN KEY (client_identity_communication_id) REFERENCES client_identity_communication (client_identity_communication_id) ON DELETE CASCADE
);


CREATE INDEX "IX_client_identity_address_mpi_link_id_source_system_name_sour~" ON client_identity_address (mpi_link_id, source_system_name, source_system_id);


CREATE INDEX "IX_client_identity_address_communication_client_identity_commu~" ON client_identity_address_communication (client_identity_communication_id);


CREATE INDEX "IX_client_identity_communication_mpi_link_id_source_system_nam~" ON client_identity_communication (mpi_link_id, source_system_name, source_system_id);


CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);


