<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HCA.Data\HCA.Data.csproj" />
    <ProjectReference Include="..\HCA.Verato\HCA.Verato.csproj" />
    <ProjectReference Include="..\HCA.Models\HCA.Models.csproj" />
    <ProjectReference Include="..\HCA.Infrastructure\HCA.Infrastructure.csproj" />
    <ProjectReference Include="..\HCA.FileProcessor\HCA.FileProcessor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Mapper\" />
    <None Remove="Microsoft.Extensions.DependencyInjection" />
    <None Remove="AutoMapper" />
    <None Remove="AutoMapper.Extensions.Microsoft.DependencyInjection" />
    <None Remove="Processors\" />
    <None Remove="Services\" />
    <None Remove="Processors\FileProcessor\" />
    <None Remove="Processors\StatusUpdater\" />
    <None Remove="Processors\SQS\" />
    <None Remove="Amazon.S3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Processors\StatusUpdater\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
  </ItemGroup>
</Project>