
namespace HCA.Models.Verato.Response;

/// <summary>
/// Post identity response content
/// </summary>
public class DOH_PostIdentityResponseContent
{
    /// <summary>
    /// <see cref="PostIdentityResponseContent"/>
    /// </summary>
    /// <param name="linkId">Link id of the post identity</param>
    /// <param name="identityGroupedBySource">Collection of identity response generated by the request <see cref="IdentityResponse"/></param>
    /// <param name="events">Collection of post identity response event <see cref="PostIdentityResponseEvent"/></param>
    public DOH_PostIdentityResponseContent(string linkId, dynamic identityGroupedBySource, dynamic events)
    {
        LinkId = linkId;
        IdentityGroupedBySource = identityGroupedBySource;
        Events = events;
    }

    /// <summary>
    /// Link id of the post identity
    /// </summary>
    public string LinkId { get; set; }

    /// <summary>
    /// Collection of identity response generated by the request <see cref="IdentityResponse"/>
    /// </summary>
    public dynamic IdentityGroupedBySource { get; set; }

    /// <summary>
    /// Collection of post identity response event <see cref="PostIdentityResponseEvent"/>
    /// </summary>
    public dynamic Events { get; set; }
}


/// <summary>
/// Post identity response content
/// </summary>
public class DOH_DemographicQueryResponseContent
{
    public DOH_DemographicQueryResponseContent()
    {
       
    }

    /// <summary>
    /// <see cref="PostIdentityResponseContent"/>
    /// </summary>
    /// <param name="linkId">Link id of the post identity</param>
    /// <param name="identityGroupedBySource">Collection of identity response generated by the request <see cref="IdentityResponse"/></param>
    public DOH_DemographicQueryResponseContent(string linkId, List<IdentityResponse> identityGroupedBySource)
    {
        LinkId = linkId;
        IdentityGroupedBySource = identityGroupedBySource;
    }

    /// <summary>
    /// Link id of the post identity
    /// </summary>
    public string LinkId { get; set; }
    public string AuditId { get; set; }

    /// <summary>
    /// Identity response generated by the request <see cref="IdentityResponse"/>
    /// </summary>
    public List<IdentityResponse> IdentityGroupedBySource { get; set; }
}
