
namespace HCA.Models.MuleSoft.Response;

/// <summary>
/// Post identity response content
/// </summary>
public class PostIdentityResponseContent
{
    /// <summary>
    /// <see cref="PostIdentityResponseContent"/>
    /// </summary>
    /// <param name="linkId">Link id of the post identity</param>
    /// <param name="identityGroupedBySource">Collection of identity response generated by the request <see cref="IdentityResponse"/></param>
    /// <param name="events">Collection of post identity response event <see cref="PostIdentityResponseEvent"/></param>
    public PostIdentityResponseContent(string linkId, List<IdentityResponse> identityGroupedBySource, List<PostIdentityResponseEvent> events)
    {
        LinkId = linkId;
        IdentityGroupedBySource = identityGroupedBySource;
        Events = events;
    }

    /// <summary>
    /// Link id of the post identity
    /// </summary>
    public string LinkId { get; set; }

    /// <summary>
    /// Collection of identity response generated by the request <see cref="IdentityResponse"/>
    /// </summary>
    public List<IdentityResponse> IdentityGroupedBySource { get; set; }

    /// <summary>
    /// Collection of post identity response event <see cref="PostIdentityResponseEvent"/>
    /// </summary>
    public List<PostIdentityResponseEvent> Events { get; set; }
}

/// <summary>
/// Post identity response content
/// </summary>
public class DeleteIdentityResponseContent
{
    public DeleteIdentityResponseContent(List<string> linkIdsModified, List<string> linkIdsDeleted)
    {
        LinkIdsModified = linkIdsModified;
        LinkIdsDeleted = linkIdsDeleted;
    }

    public List<string> LinkIdsModified { get; set; }

    public List<string> LinkIdsDeleted { get; set; }
}

/// <summary>
/// Post identity response content
/// </summary>
public class DemographicQueryResponseContent
{
    public DemographicQueryResponseContent()
    {
       
    }

    /// <summary>
    /// <see cref="PostIdentityResponseContent"/>
    /// </summary>
    /// <param name="linkId">Link id of the post identity</param>
    /// <param name="identity">Collection of identity response generated by the request <see cref="IdentityResponse"/></param>
    public DemographicQueryResponseContent(string linkId, List<IdentityResponse> identityGroupedBySource)
    {
        LinkId = linkId;
        IdentityGroupedBySource = identityGroupedBySource;
    }

    /// <summary>
    /// Link id of the post identity
    /// </summary>
    public string LinkId { get; set; }
    public string auditId { get; set; }

    /// <summary>
    /// Identity response generated by the request <see cref="IdentityResponse"/>
    /// </summary>
    public List<IdentityResponse> IdentityGroupedBySource { get; set; }

}
