<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.4" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Microsoft.Extensions.Configuration" />
    <None Remove="Microsoft.Extensions.Configuration.Binder" />
    <None Remove="Microsoft.Extensions.Configuration.Json" />
    <None Remove="Microsoft.Extensions.DependencyInjection" />
    <None Remove="Amazon.S3" />
    <None Remove="AWSSDK.S3" />
    <None Remove="Models\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\HCA.Core\HCA.Core.csproj" />
    <ProjectReference Include="..\..\..\HCA.Data\HCA.Data.csproj" />
    <ProjectReference Include="..\..\..\HCA.Infrastructure\HCA.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\HCA.Models\HCA.Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
</Project>